- name: Install unit file
  sudo: true
  copy: src=mysql.service dest=/lib/systemd/system/ owner=root mode=644
  notify:
    - reload systemd
    - restart mysql

- shell: systemctl enable mysql
  sudo: yes
